/* Generated By:JavaCC: Do not edit this line. JSONParserConstants.java */
package de.schlund.pfixcore.webservice.json.parser;

public interface JSONParserConstants {

  int EOF = 0;
  int LCB = 6;
  int RCB = 7;
  int LSB = 8;
  int RSB = 9;
  int COL = 10;
  int COM = 11;
  int TRUE = 12;
  int FALSE = 13;
  int NULL = 14;
  int QSTR = 15;
  int HEX = 16;
  int NUM = 17;
  int DATE = 18;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\",\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<QSTR>",
    "<HEX>",
    "<NUM>",
    "<DATE>",
  };

}
