/*
 * de.schlund.pfixcore.webservice.generate.js.JsClass
 */
package de.schlund.pfixcore.webservice.generate.js;

import java.io.IOException;
import java.io.OutputStream;
import java.util.StringTokenizer;

/**
 * JsClass.java 
 * 
 * Created: 30.08.2004
 * 
 * @author mleidig
 */
public class JsClass {

    String name;
    String baseName;
    JsMethod[] methods;
    JsBlock constBody;
    JsParam[] constParams;
    
    public JsClass(String name,String baseName,JsParam[] constParams) {
        this.name=name;
        this.baseName=baseName;
        methods=new JsMethod[0];
        constBody=new JsBlock();
        this.constParams=constParams;
    }
    
    public String getName() {
        return name;
    }
    
    public String getBaseName() {
        return baseName;
    }
    
    public void addMethod(JsMethod method) {
        JsMethod[] upd=new JsMethod[methods.length+1];
        for(int i=0;i<methods.length;i++) upd[i]=methods[i];
        upd[upd.length-1]=method;
        methods=upd;
    }
    
    public JsMethod[] getMethods() {
        return methods;
    }
    
    public JsBlock getConstructorBody() {
        return constBody;
    }
    
    public String getConstructorParamList() {
        StringBuffer sb=new StringBuffer();
        for(int i=0;i<constParams.length;i++) {
            sb.append(constParams[i].getName());
            if(i<constParams.length-1) sb.append(",");
        }
        return sb.toString();
    }
    
    public void printCode(OutputStream out) throws IOException {
        StringBuffer sb=new StringBuffer();
        sb.append("//Autogenerated webservice stub (don't modify this code manually!)\n");
        if(getName().contains(".")) {
            StringTokenizer st=new StringTokenizer(getName(),".");
            String subNs=null;
            while(st.hasMoreTokens()) {
                String ns=st.nextToken();
                if(subNs==null) {
                    sb.append("if(!window."+ns+") "+ns+"={};\n");
                    subNs=ns;
                } else if(st.hasMoreTokens()) {
                    subNs=subNs+"."+ns;
                    sb.append("if(!"+subNs+") "+subNs+"={};\n");
                }
            }
        }
        sb.append("function "+getName()+"("+getConstructorParamList()+") {\n");
        out.write(sb.toString().getBytes());
        getConstructorBody().printCode("  ",out);
        sb=new StringBuffer();
        sb.append("}\n");
        sb.append(name+".prototype=new "+baseName+";\n");
        out.write(sb.toString().getBytes());
        for(int i=0;i<methods.length;i++) methods[i].printCode("  ",out);  
    }
    
}
