/*
 * de.schlund.pfixcore.webservice.generate.js.JsClass
 */
package de.schlund.pfixcore.webservice.generate.js;

import java.io.IOException;
import java.io.OutputStream;

/**
 * JsClass.java 
 * 
 * Created: 30.08.2004
 * 
 * @author mleidig
 */
public class JsClass {

    String name;
    JsMethod[] methods;
    JsBlock constBody;
    
    public JsClass(String name) {
        this.name=name;
        methods=new JsMethod[0];
        constBody=new JsBlock();
    }
    
    public String getName() {
        return name;
    }
    
    public void addMethod(JsMethod method) {
        JsMethod[] upd=new JsMethod[methods.length+1];
        for(int i=0;i<methods.length;i++) upd[i]=methods[i];
        upd[upd.length-1]=method;
        methods=upd;
    }
    
    public JsMethod[] getMethods() {
        return methods;
    }
    
    public JsBlock getConstructorBody() {
        return constBody;
    }
    
    public void printCode(OutputStream out) throws IOException {
        System.out.println("//Autogenerated webservice stub (don't modify this code manually!)");
        StringBuffer sb=new StringBuffer();
        sb.append("function "+getName()+"() {\n");
        out.write(sb.toString().getBytes());
        getConstructorBody().printCode("  ",out);
        out.write("}\n".getBytes());
        for(int i=0;i<methods.length;i++) methods[i].printCode("  ",out);  
    }
    
}
